#!/bin/bash

. /opt/helpers

echo "=> Starting Icinga Daemon"
icinga2 daemon &
ICINGA2_PID=$!
echo "==> PID: $ICINGA2_PID"

# Kickstart is only possible after icinga2 start -> not in setup script
if    evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR}" \
   && evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR_KICKSTART}"; then
    echo "=> Running Icinga Director Kickstarter"
    # todo check if icinga is up another way
    sleep 10s
	icingacli director kickstart run
    echo "=> Running Icinga Director Kickstarter...done"
fi

# Allow any signal which would kill a process to stop server
trap "kill $ICINGA2_PID" HUP INT QUIT ABRT ALRM TERM TSTP

wait $ICINGA2_PID
