#!/bin/bash

. /opt/helpers

echo "=> Starting Icinga Daemon"
icinga2 daemon &

# Kickstart is only possible after icinga2 start -> not in setup script
if    evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR}" \
   && evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR_KICKSTART}"; then
    echo "=> Running Icinga Director Kickstart"
    # todo check if icinga is up another way
    sleep 10s
    echo "=> Migrate the Icinga Director database"
    icingacli director migration run
    echo "=> Check if a Kickstart configuration is required"
    if icingacli director kickstart required --verbose | grep -q 'should be triggered'; then
        echo "==> Kickstart configuration is required"
        echo "==> Running Kickstarter configuration, killing after 10s"
        icingacli director kickstart run &
        KICKSTARTERPID=$!
        sleep 10
        kill $KICKSTARTERPID
        echo "==> Running Kickstarter configuration, killing after 10s...done"
        echo "==> Deploying new configuration, restarting Icinga2"
        icingacli director config deploy
    fi
fi

echo "=> Icinga2 boot complete"

# Allow any signal which would kill a process to stop server
trap "killall icinga2" HUP INT QUIT ABRT ALRM TERM TSTP

i=0
while [ $i -lt 5 ] ; do
    sleep 5
    if pgrep -x "icinga2" > /dev/null
    then
        i=0
    else
        i=$[$i+1]
        echo "=> No icinga process found ($i)"
    fi
done
