#!/bin/bash

. /opt/helpers

CNFSUFFIX=icinga2
mysql_cnf_init_section \
	"${CNFSUFFIX}" \
	"${ICINGA2_IDO_MYSQL_HOST}" \
	"${ICINGA2_IDO_MYSQL_PORT}" \
	"${ICINGA2_IDO_MYSQL_USER}" \
	"${ICINGA2_IDO_MYSQL_DATA}" \
	"${ICINGA2_IDO_MYSQL_PASS}"
mysql_wait \
	"${ICINGA2_IDO_MYSQL_HOST}" \
	"${ICINGA2_IDO_MYSQL_PORT}"

if [ ! "$(ls -A /usr/local/etc/icinga2)" ]; then
	echo "=> Copying fresh config-files for /usr/local/etc/icinga2"
	cp -R /usr/local/etc/icinga2.dist/* /usr/local/etc/icinga2/
fi

chown -R icinga:www-data /usr/local/var/cache/icinga2
chown -R icinga:www-data /usr/local/var/log/icinga2
chown -R icinga:www-data /usr/local/var/run/icinga2
chown -R icinga:www-data /usr/local/var/lib/icinga2

# enable necessary features
icinga2 feature enable ido-mysql livestatus compatlog command

#icinga2 API cert - regenerate new private key and certificate when running in a new container
# todo check this
if [ ! -f "/etc/icinga2/pki/$(hostname).key" ]; then
	icinga2 node setup --master
fi

# Create MySQL user on localhost or test given connection
if [ "${ICINGA2_IDO_MYSQL_HOST}" == "localhost" ]; then
	mysql_root <<-END
	  CREATE DATABASE IF NOT EXISTS ${ICINGA2_IDO_MYSQL_DATA};
	  GRANT ALL
	    ON ${ICINGA2_IDO_MYSQL_DATA}.*
	    TO '${ICINGA2_IDO_MYSQL_USER}'@'localhost'
	    IDENTIFIED BY '${ICINGA2_IDO_MYSQL_PASS}';
	END
elif [ -n "${MYSQL_ROOT_PASSWORD:-}" ]; then
	mysql_root <<-END
	  CREATE DATABASE IF NOT EXISTS ${ICINGA2_IDO_MYSQL_DATA};
	  GRANT ALL
	    ON ${ICINGA2_IDO_MYSQL_DATA}.*
	    TO '${ICINGA2_IDO_MYSQL_USER}'@'%'
	    IDENTIFIED BY '${ICINGA2_IDO_MYSQL_PASS}';
	END
fi

echo "=> Testing MySQL credentials"
mysql_test_credentials
echo "=> Testing MySQL credentials...success"

mysql_user \
	< /usr/share/icinga2/lib/db_ido_mysql/schema/mysql.sql \
	>> /usr/local/var/log/icinga2/mysql-schema.log \
	2>&1 || true

cat > /usr/local/etc/icinga2/features-available/ido-mysql.conf <<-END
/**
 * The db_ido_mysql library implements IDO functionality
 * for MySQL.
 */

library "db_ido_mysql"

object IdoMysqlConnection "ido-mysql" {
  user     = "${ICINGA2_IDO_MYSQL_USER}"
  password = "${ICINGA2_IDO_MYSQL_PASS}"
  host     = "${ICINGA2_IDO_MYSQL_HOST}"
  port     =  ${ICINGA2_IDO_MYSQL_PORT}
  database = "${ICINGA2_IDO_MYSQL_DATA}"
}
END
